version: '3.8'

services:
  omdb-db:
    container_name: omdb
    image: mysql
    volumes:
      - ./omdb-db_academy_awards.sql:/docker-entrypoint-initdb.d/dump.sql
      - omdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: haselko
      MYSQL_DATABASE: omdb-db
    ports:
      - 3307:3306

volumes:
  omdb:
